feat: Vercel Deployment
tscircuit/add-pr-comment-proxy pull request #5
Opened 2024-11-24 01:31 UTC by melmathari

# add-pr-comment-proxy

A simple proxy for PR comments. Works well with [add-pr-comment](https://github.com/mshick/add-pr-comment/). Workaround for GitHub making all token permissions read-only when a fork is submitted for a PR. See [this discussion](https://github.community/t/github-actions-are-severely-limited-on-prs/18179/4) for more detail.

## Deploy

**Requirements**

- A [personal access token](https://github.com/settings/tokens) with the `repo:public_repos` scope if you're using this to support a public repo. Your use-case might require other scopes.

**Run on Cloud Run**

[![Run on Google Cloud](https://deploy.cloud.run/button.svg)](https://deploy.cloud.run)

## How it works

This app is a thin Node.js proxy around the [create an issue comment](https://docs.github.com/en/rest/reference/issues#create-an-issue-comment) GitHub endpoint that allows you to send requests with a GitHub Action's [temporary token](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret) and create issue comments. It verifies that your request has a valid temporary token, but it's difficult to ensure any more than that. A shared secret cannot be used as GitHub will strip it when the fork's Actions run.

/claim #2

2024-11-24 08:36 UTC, seveibar commented on .vercel/README.txt
> +No, you should not share the ".vercel" folder with anyone.
☝️

2024-11-24 08:37 UTC, seveibar approved these changes
Looks good , but see comment

2024-11-24 08:38 UTC, seveibar requested changes
Woops see comment, dont commit Vercel dir

2024-11-24 10:48 UTC, melmathari commented
> Woops see comment, dont commit Vercel dir

Hi @seveibar I've updated the comment on line 10, thanks for pointing it out!

2024-11-24 12:53 UTC, seveibar commented
Incorrect, read closely.

2024-11-24 13:42 UTC, melmathari commented
> Incorrect, read closely.

@seveibar Thanks for your time. I just see a finger pointing up, and I'm not sure what change is needed. Should I change "folder" to "dir"? Thanks!

![image](https://github.com/user-attachments/assets/9ceb7626-91a0-459e-806c-9ee48825a259)

2024-11-24 21:17 UTC, seveibar commented
![image](https://github.com/user-attachments/assets/31b666e7-9fc8-4f55-ab35-ae55f030461b)

As already stated, dont commit the vercel directory. The finger is pointing to the recommendation

2024-11-24 22:52 UTC, melmathari commented
@seveibar Thanks for catching that! My mistake... I appreciate you taking the time to point it out

2024-11-25 00:12 UTC, seveibar commented on README.md
> +**Important:** Add `.vercel` to your `.gitignore` file to prevent accidentally committing it.
```suggestion
```

2024-11-25 00:15 UTC, seveibar commented
@melmathari alright after reviewing this code, it's just got wayyy too many issues. For example it uses `@actions/*` which should never be used from within Vercel, I'd like someone else to implement this feature using a more conventional nextjs style api route.

2024-11-25 00:15 UTC, closed without merging

2024-11-25 00:29 UTC, seveibar commented
@actions/* might be usable from within vercel, however still no evidence provided in the PR that this works.  The PR description confusingly mentions google cloud run.